"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { dataErrorMessage, dataProvider, dataProviderMode, type Item, type ItemStatus, type ItemType as DataItemType } from "@/lib/data";
import { ErrorState, LoadingState } from "@/components/ui-states";
import { Icon, itemIcon } from "@/components/icons";
import { ItemType } from "@/components/item-type";
import { useWorkspace } from "@/components/workspace-context";

const captureModes: { type: DataItemType; label: string }[] = [{ type:"note", label:"Write note" }, { type:"url", label:"Paste URL" }, { type:"file", label:"Upload file" }, { type:"audio", label:"Voice coming soon" }];
const shortTime = (date: string) => { const min = Math.max(0, Math.round((Date.now() - new Date(date).getTime()) / 60000)); return min < 1 ? "Just now" : min < 60 ? `${min}m ago` : min < 1440 ? `${Math.round(min / 60)}h ago` : "Yesterday"; };
export function DashboardPage() {
  const { openCapture } = useWorkspace();
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [mode, setMode] = useState<DataItemType>("note"); const [value, setValue] = useState(""); const [status, setStatus] = useState<ItemStatus | null>(null);
  const load = async () => { try { setError(null); setItems(await dataProvider.listItems({ limit:5 })); } catch (caught) { setError(dataErrorMessage(caught, "Your recent items could not be loaded.")); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const capture = async () => { try { setError(null); const payload = mode === "url" ? { type:"url" as const, sourceUrl:value, content:value } : { type:"note" as const, content:value }; await dataProvider.trackEvent({ eventType:"capture_started", targetType:"capture" }); const next = await dataProvider.createItem(payload); void dataProvider.trackEvent({ eventType:"capture_submitted", targetType:"item", targetId:next.id, metadata:{ sourceType:payload.type } }); setItems(await dataProvider.listItems({ limit:5 })); setValue(""); setStatus(next.status); window.setTimeout(() => setStatus(null), 2400); } catch (caught) { setError(dataErrorMessage(caught, "Capture failed. Try again.")); } };
  const ready = Boolean(value.trim());
  return <div className="mx-auto max-w-4xl space-y-8 px-4 py-8 sm:px-8 sm:py-10"><section className="border-b hairline pb-4"><h1 className="text-[24px] font-semibold tracking-[-.03em]">Good morning, Alex</h1><p className="mt-1 text-slate-500">Your project memory and recent Flares.</p></section>
  <section className="overflow-hidden rounded-xl border hairline bg-white"><div className="flex overflow-x-auto border-b hairline px-3 pt-3"><div className="flex gap-1">{captureModes.map((entry) => <button key={entry.type} disabled={entry.type === "audio"} onClick={() => { if (entry.type === "file") { openCapture(); return; } setMode(entry.type); setValue(""); }} className={`focus-ring inline-flex shrink-0 items-center gap-1.5 rounded-md px-3 py-1.5 text-[13px] disabled:cursor-not-allowed disabled:opacity-45 ${mode === entry.type ? "border hairline bg-slate-50 font-medium" : "text-slate-500 hover:bg-slate-50 hover:text-slate-950"}`}><Icon name={itemIcon[entry.type]} className="h-4 w-4"/>{entry.label}</button>)}</div></div>
  <div className="p-3"><textarea value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if ((event.metaKey || event.ctrlKey) && event.key === "Enter" && ready) void capture(); }} rows={3} className="focus-ring w-full resize-none rounded p-1 text-[15px] leading-relaxed outline-none" placeholder={mode === "url" ? "Paste a URL to keep it close…" : "Drop thoughts, meeting notes, decisions, paste links, or press ⌘Enter…"}/></div>
  <div className="flex items-center justify-between border-t hairline bg-slate-50/70 px-3 py-2.5"><span className="mono text-[10px] text-slate-500">{status === "processing" ? "Saved · processing" : dataProviderMode === "api" ? "Stored in PostgreSQL" : "Stored locally in this MVP"}</span><button disabled={!ready} onClick={() => void capture()} className="focus-ring rounded-md bg-slate-950 px-4 py-1.5 text-[13px] font-medium text-white disabled:cursor-not-allowed disabled:opacity-35">Capture</button></div></section>
  {error && <ErrorState message={error}/>}<div className="grid items-start gap-8 lg:grid-cols-12"><section className="space-y-3 lg:col-span-7"><div className="flex items-center justify-between"><h2 className="font-semibold">Recently Added</h2><Link className="text-xs text-slate-500 hover:text-slate-950" href="/vault">View all</Link></div><div className="overflow-hidden rounded-xl border hairline bg-white divide-y divide-slate-100">{loading ? <LoadingState/> : items.map((item) => <Link href={`/vault?item=${item.id}`} key={item.id} className="flex items-center justify-between gap-3 p-3.5 hover:bg-slate-50"><span className="flex min-w-0 items-center gap-2.5"><Icon name={itemIcon[item.type]} className="h-[17px] w-[17px] shrink-0 text-slate-500"/><span className="truncate font-medium">{item.title}</span></span><span className="flex shrink-0 items-center gap-2"><span className="hidden sm:block"><ItemType type={item.type}/></span>{item.status === "processing" && <span className="rounded bg-slate-100 px-2 py-0.5 text-[11px] text-slate-600">Processing…</span>}<time className="text-xs text-slate-500">{shortTime(item.createdAt)}</time></span></Link>)}</div></section>
  <RecentInsights/></div></div>;
}
function RecentInsights() { const [insights, setInsights] = useState<Awaited<ReturnType<typeof dataProvider.listInsights>>>([]); useEffect(() => { void dataProvider.listInsights().then(setInsights); }, []); return <section className="space-y-3 lg:col-span-5"><h2 className="font-semibold">Recent Flares</h2><div className="space-y-3">{insights.slice(0,2).map((insight) => <Link key={insight.id} href={`/insights?insight=${insight.id}`} className="block space-y-2.5 rounded-xl border hairline bg-white p-4 hover:border-slate-300"><h3 className="font-semibold leading-snug">{insight.title}</h3><p className="leading-relaxed text-slate-500">{insight.statement}</p><div className="flex justify-between border-t hairline pt-2 text-xs text-slate-500"><span>Updated {shortTime(insight.createdAt)}</span><span className="font-medium text-slate-950">{insight.evidence.length} pieces of evidence →</span></div></Link>)}</div></section>; }
